import adSvg from "@/assets/flags/ad.svg";
import aeSvg from "@/assets/flags/ae.svg";
import afSvg from "@/assets/flags/af.svg";
import agSvg from "@/assets/flags/ag.svg";
import aiSvg from "@/assets/flags/ai.svg";
import alSvg from "@/assets/flags/al.svg";
import amSvg from "@/assets/flags/am.svg";
import aoSvg from "@/assets/flags/ao.svg";
import aqSvg from "@/assets/flags/aq.svg";
import arSvg from "@/assets/flags/ar.svg";
import asSvg from "@/assets/flags/as.svg";
import atSvg from "@/assets/flags/at.svg";
import auSvg from "@/assets/flags/au.svg";
import awSvg from "@/assets/flags/aw.svg";
import axSvg from "@/assets/flags/ax.svg";
import azSvg from "@/assets/flags/az.svg";
import baSvg from "@/assets/flags/ba.svg";
import bbSvg from "@/assets/flags/bb.svg";
import bdSvg from "@/assets/flags/bd.svg";
import beSvg from "@/assets/flags/be.svg";
import bfSvg from "@/assets/flags/bf.svg";
import bgSvg from "@/assets/flags/bg.svg";
import bhSvg from "@/assets/flags/bh.svg";
import biSvg from "@/assets/flags/bi.svg";
import bjSvg from "@/assets/flags/bj.svg";
import blSvg from "@/assets/flags/bl.svg";
import bmSvg from "@/assets/flags/bm.svg";
import bnSvg from "@/assets/flags/bn.svg";
import boSvg from "@/assets/flags/bo.svg";
import bqSvg from "@/assets/flags/bq.svg";
import brSvg from "@/assets/flags/br.svg";
import bsSvg from "@/assets/flags/bs.svg";
import btSvg from "@/assets/flags/bt.svg";
import bvSvg from "@/assets/flags/bv.svg";
import bwSvg from "@/assets/flags/bw.svg";
import bySvg from "@/assets/flags/by.svg";
import bzSvg from "@/assets/flags/bz.svg";
import caSvg from "@/assets/flags/ca.svg";
import ccSvg from "@/assets/flags/cc.svg";
import cdSvg from "@/assets/flags/cd.svg";
import cfSvg from "@/assets/flags/cf.svg";
import cgSvg from "@/assets/flags/cg.svg";
import chSvg from "@/assets/flags/ch.svg";
import ciSvg from "@/assets/flags/ci.svg";
import ckSvg from "@/assets/flags/ck.svg";
import clSvg from "@/assets/flags/cl.svg";
import cmSvg from "@/assets/flags/cm.svg";
import cnSvg from "@/assets/flags/cn.svg";
import coSvg from "@/assets/flags/co.svg";
import crSvg from "@/assets/flags/cr.svg";
import cuSvg from "@/assets/flags/cu.svg";
import cvSvg from "@/assets/flags/cv.svg";
import cwSvg from "@/assets/flags/cw.svg";
import cxSvg from "@/assets/flags/cx.svg";
import cySvg from "@/assets/flags/cy.svg";
import czSvg from "@/assets/flags/cz.svg";
import deSvg from "@/assets/flags/de.svg";
import djSvg from "@/assets/flags/dj.svg";
import dkSvg from "@/assets/flags/dk.svg";
import dmSvg from "@/assets/flags/dm.svg";
import doSvg from "@/assets/flags/do.svg";
import dzSvg from "@/assets/flags/dz.svg";
import ecSvg from "@/assets/flags/ec.svg";
import eeSvg from "@/assets/flags/ee.svg";
import egSvg from "@/assets/flags/eg.svg";
import ehSvg from "@/assets/flags/eh.svg";
import erSvg from "@/assets/flags/er.svg";
import esSvg from "@/assets/flags/es.svg";
import etSvg from "@/assets/flags/et.svg";
import euSvg from "@/assets/flags/eu.svg";
import fiSvg from "@/assets/flags/fi.svg";
import fjSvg from "@/assets/flags/fj.svg";
import fkSvg from "@/assets/flags/fk.svg";
import fmSvg from "@/assets/flags/fm.svg";
import foSvg from "@/assets/flags/fo.svg";
import frSvg from "@/assets/flags/fr.svg";
import gaSvg from "@/assets/flags/ga.svg";
import gbEngSvg from "@/assets/flags/gb-eng.svg";
import gbNirSvg from "@/assets/flags/gb-nir.svg";
import gbSctSvg from "@/assets/flags/gb-sct.svg";
import gbWlsSvg from "@/assets/flags/gb-wls.svg";
import gbSvg from "@/assets/flags/gb.svg";
import gdSvg from "@/assets/flags/gd.svg";
import geSvg from "@/assets/flags/ge.svg";
import gfSvg from "@/assets/flags/gf.svg";
import ggSvg from "@/assets/flags/gg.svg";
import ghSvg from "@/assets/flags/gh.svg";
import giSvg from "@/assets/flags/gi.svg";
import glSvg from "@/assets/flags/gl.svg";
import gmSvg from "@/assets/flags/gm.svg";
import gnSvg from "@/assets/flags/gn.svg";
import gpSvg from "@/assets/flags/gp.svg";
import gqSvg from "@/assets/flags/gq.svg";
import grSvg from "@/assets/flags/gr.svg";
import gsSvg from "@/assets/flags/gs.svg";
import gtSvg from "@/assets/flags/gt.svg";
import guSvg from "@/assets/flags/gu.svg";
import gwSvg from "@/assets/flags/gw.svg";
import gySvg from "@/assets/flags/gy.svg";
import hkSvg from "@/assets/flags/hk.svg";
import hmSvg from "@/assets/flags/hm.svg";
import hnSvg from "@/assets/flags/hn.svg";
import hrSvg from "@/assets/flags/hr.svg";
import htSvg from "@/assets/flags/ht.svg";
import huSvg from "@/assets/flags/hu.svg";
import idSvg from "@/assets/flags/id.svg";
import ieSvg from "@/assets/flags/ie.svg";
import ilSvg from "@/assets/flags/il.svg";
import imSvg from "@/assets/flags/im.svg";
import inSvg from "@/assets/flags/in.svg";
import ioSvg from "@/assets/flags/io.svg";
import iqSvg from "@/assets/flags/iq.svg";
import irSvg from "@/assets/flags/ir.svg";
import isSvg from "@/assets/flags/is.svg";
import itSvg from "@/assets/flags/it.svg";
import jeSvg from "@/assets/flags/je.svg";
import jmSvg from "@/assets/flags/jm.svg";
import joSvg from "@/assets/flags/jo.svg";
import jpSvg from "@/assets/flags/jp.svg";
import keSvg from "@/assets/flags/ke.svg";
import kgSvg from "@/assets/flags/kg.svg";
import khSvg from "@/assets/flags/kh.svg";
import kiSvg from "@/assets/flags/ki.svg";
import kmSvg from "@/assets/flags/km.svg";
import knSvg from "@/assets/flags/kn.svg";
import kpSvg from "@/assets/flags/kp.svg";
import krSvg from "@/assets/flags/kr.svg";
import kwSvg from "@/assets/flags/kw.svg";
import kySvg from "@/assets/flags/ky.svg";
import kzSvg from "@/assets/flags/kz.svg";
import laSvg from "@/assets/flags/la.svg";
import lbSvg from "@/assets/flags/lb.svg";
import lcSvg from "@/assets/flags/lc.svg";
import liSvg from "@/assets/flags/li.svg";
import lkSvg from "@/assets/flags/lk.svg";
import lrSvg from "@/assets/flags/lr.svg";
import lsSvg from "@/assets/flags/ls.svg";
import ltSvg from "@/assets/flags/lt.svg";
import luSvg from "@/assets/flags/lu.svg";
import lvSvg from "@/assets/flags/lv.svg";
import lySvg from "@/assets/flags/ly.svg";
import maSvg from "@/assets/flags/ma.svg";
import mcSvg from "@/assets/flags/mc.svg";
import mdSvg from "@/assets/flags/md.svg";
import meSvg from "@/assets/flags/me.svg";
import mfSvg from "@/assets/flags/mf.svg";
import mgSvg from "@/assets/flags/mg.svg";
import mhSvg from "@/assets/flags/mh.svg";
import mkSvg from "@/assets/flags/mk.svg";
import mlSvg from "@/assets/flags/ml.svg";
import mmSvg from "@/assets/flags/mm.svg";
import mnSvg from "@/assets/flags/mn.svg";
import moSvg from "@/assets/flags/mo.svg";
import mpSvg from "@/assets/flags/mp.svg";
import mqSvg from "@/assets/flags/mq.svg";
import mrSvg from "@/assets/flags/mr.svg";
import msSvg from "@/assets/flags/ms.svg";
import mtSvg from "@/assets/flags/mt.svg";
import muSvg from "@/assets/flags/mu.svg";
import mvSvg from "@/assets/flags/mv.svg";
import mwSvg from "@/assets/flags/mw.svg";
import mxSvg from "@/assets/flags/mx.svg";
import mySvg from "@/assets/flags/my.svg";
import mzSvg from "@/assets/flags/mz.svg";
import naSvg from "@/assets/flags/na.svg";
import ncSvg from "@/assets/flags/nc.svg";
import neSvg from "@/assets/flags/ne.svg";
import nfSvg from "@/assets/flags/nf.svg";
import ngSvg from "@/assets/flags/ng.svg";
import niSvg from "@/assets/flags/ni.svg";
import nlSvg from "@/assets/flags/nl.svg";
import noSvg from "@/assets/flags/no.svg";
import npSvg from "@/assets/flags/np.svg";
import nrSvg from "@/assets/flags/nr.svg";
import nuSvg from "@/assets/flags/nu.svg";
import nzSvg from "@/assets/flags/nz.svg";
import omSvg from "@/assets/flags/om.svg";
import paSvg from "@/assets/flags/pa.svg";
import peSvg from "@/assets/flags/pe.svg";
import pfSvg from "@/assets/flags/pf.svg";
import pgSvg from "@/assets/flags/pg.svg";
import phSvg from "@/assets/flags/ph.svg";
import pkSvg from "@/assets/flags/pk.svg";
import plSvg from "@/assets/flags/pl.svg";
import pmSvg from "@/assets/flags/pm.svg";
import pnSvg from "@/assets/flags/pn.svg";
import prSvg from "@/assets/flags/pr.svg";
import psSvg from "@/assets/flags/ps.svg";
import ptSvg from "@/assets/flags/pt.svg";
import pwSvg from "@/assets/flags/pw.svg";
import pySvg from "@/assets/flags/py.svg";
import qaSvg from "@/assets/flags/qa.svg";
import reSvg from "@/assets/flags/re.svg";
import roSvg from "@/assets/flags/ro.svg";
import rsSvg from "@/assets/flags/rs.svg";
import ruSvg from "@/assets/flags/ru.svg";
import rwSvg from "@/assets/flags/rw.svg";
import saSvg from "@/assets/flags/sa.svg";
import sbSvg from "@/assets/flags/sb.svg";
import scSvg from "@/assets/flags/sc.svg";
import sdSvg from "@/assets/flags/sd.svg";
import seSvg from "@/assets/flags/se.svg";
import sgSvg from "@/assets/flags/sg.svg";
import shSvg from "@/assets/flags/sh.svg";
import siSvg from "@/assets/flags/si.svg";
import sjSvg from "@/assets/flags/sj.svg";
import skSvg from "@/assets/flags/sk.svg";
import slSvg from "@/assets/flags/sl.svg";
import smSvg from "@/assets/flags/sm.svg";
import snSvg from "@/assets/flags/sn.svg";
import soSvg from "@/assets/flags/so.svg";
import srSvg from "@/assets/flags/sr.svg";
import ssSvg from "@/assets/flags/ss.svg";
import stSvg from "@/assets/flags/st.svg";
import svSvg from "@/assets/flags/sv.svg";
import sxSvg from "@/assets/flags/sx.svg";
import sySvg from "@/assets/flags/sy.svg";
import szSvg from "@/assets/flags/sz.svg";
import tcSvg from "@/assets/flags/tc.svg";
import tdSvg from "@/assets/flags/td.svg";
import tfSvg from "@/assets/flags/tf.svg";
import tgSvg from "@/assets/flags/tg.svg";
import thSvg from "@/assets/flags/th.svg";
import tjSvg from "@/assets/flags/tj.svg";
import tkSvg from "@/assets/flags/tk.svg";
import tlSvg from "@/assets/flags/tl.svg";
import tmSvg from "@/assets/flags/tm.svg";
import tnSvg from "@/assets/flags/tn.svg";
import toSvg from "@/assets/flags/to.svg";
import trSvg from "@/assets/flags/tr.svg";
import ttSvg from "@/assets/flags/tt.svg";
import tvSvg from "@/assets/flags/tv.svg";
import twSvg from "@/assets/flags/tw.svg";
import tzSvg from "@/assets/flags/tz.svg";
import uaSvg from "@/assets/flags/ua.svg";
import ugSvg from "@/assets/flags/ug.svg";
import umSvg from "@/assets/flags/um.svg";
import usSvg from "@/assets/flags/us.svg";
import uySvg from "@/assets/flags/uy.svg";
import uzSvg from "@/assets/flags/uz.svg";
import vaSvg from "@/assets/flags/va.svg";
import vcSvg from "@/assets/flags/vc.svg";
import veSvg from "@/assets/flags/ve.svg";
import vgSvg from "@/assets/flags/vg.svg";
import viSvg from "@/assets/flags/vi.svg";
import vnSvg from "@/assets/flags/vn.svg";
import vuSvg from "@/assets/flags/vu.svg";
import wfSvg from "@/assets/flags/wf.svg";
import wsSvg from "@/assets/flags/ws.svg";
import xkSvg from "@/assets/flags/xk.svg";
import yeSvg from "@/assets/flags/ye.svg";
import ytSvg from "@/assets/flags/yt.svg";
import zaSvg from "@/assets/flags/za.svg";
import zmSvg from "@/assets/flags/zm.svg";
import zwSvg from "@/assets/flags/zw.svg";
import notFoundSvg from "@/assets/flags/notFound.svg";

export function getFlagFromText(text: string) {
  const lowercaseText = text.toLowerCase();
  if (lowercaseText.includes("andorra")) return adSvg.src;
  if (lowercaseText.includes("united arab emirates")) return aeSvg.src;
  if (lowercaseText.includes("afghanistan")) return afSvg.src;
  if (lowercaseText.includes("antigua and barbuda")) return agSvg.src;
  if (lowercaseText.includes("anguilla")) return aiSvg.src;
  if (lowercaseText.includes("albania")) return alSvg.src;
  if (lowercaseText.includes("armenia")) return amSvg.src;
  if (lowercaseText.includes("angola")) return aoSvg.src;
  if (lowercaseText.includes("antarctica")) return aqSvg.src;
  if (lowercaseText.includes("argentina")) return arSvg.src;
  if (lowercaseText.includes("american samoa")) return asSvg.src;
  if (lowercaseText.includes("austria")) return atSvg.src;
  if (lowercaseText.includes("australia")) return auSvg.src;
  if (lowercaseText.includes("aruba")) return awSvg.src;
  if (lowercaseText.includes("aland islands")) return axSvg.src;
  if (lowercaseText.includes("azerbaijan")) return azSvg.src;
  if (lowercaseText.includes("bosnia and herzegovina")) return baSvg.src;
  if (lowercaseText.includes("barbados")) return bbSvg.src;
  if (lowercaseText.includes("bangladesh")) return bdSvg.src;
  if (lowercaseText.includes("belgium")) return beSvg.src;
  if (lowercaseText.includes("burkina faso")) return bfSvg.src;
  if (lowercaseText.includes("bulgaria")) return bgSvg.src;
  if (lowercaseText.includes("bahrain")) return bhSvg.src;
  if (lowercaseText.includes("burundi")) return biSvg.src;
  if (lowercaseText.includes("benin")) return bjSvg.src;
  if (lowercaseText.includes("saint barthelemy")) return blSvg.src;
  if (lowercaseText.includes("bermuda")) return bmSvg.src;
  if (lowercaseText.includes("brunei darussalam")) return bnSvg.src;
  if (lowercaseText.includes("bolivia")) return boSvg.src;
  if (lowercaseText.includes("bonaire, sint eustatius and saba"))
    return bqSvg.src;
  if (lowercaseText.includes("brazil")) return brSvg.src;
  if (lowercaseText.includes("bahamas")) return bsSvg.src;
  if (lowercaseText.includes("bhutan")) return btSvg.src;
  if (lowercaseText.includes("bouvet island")) return bvSvg.src;
  if (lowercaseText.includes("botswana")) return bwSvg.src;
  if (lowercaseText.includes("belarus")) return bySvg.src;
  if (lowercaseText.includes("belize")) return bzSvg.src;
  if (lowercaseText.includes("canada")) return caSvg.src;
  if (lowercaseText.includes("cocos (keeling) islands")) return ccSvg.src;
  if (lowercaseText.includes("congo, the democratic republic of the"))
    return cdSvg.src;
  if (lowercaseText.includes("central african republic")) return cfSvg.src;
  if (lowercaseText.includes("congo")) return cgSvg.src;
  if (lowercaseText.includes("switzerland")) return chSvg.src;
  if (lowercaseText.includes("cote d'ivoire")) return ciSvg.src;
  if (lowercaseText.includes("cook islands")) return ckSvg.src;
  if (lowercaseText.includes("chile")) return clSvg.src;
  if (lowercaseText.includes("cameroon")) return cmSvg.src;
  if (lowercaseText.includes("china")) return cnSvg.src;
  if (lowercaseText.includes("colombia")) return coSvg.src;
  if (lowercaseText.includes("costa rica")) return crSvg.src;
  if (lowercaseText.includes("cuba")) return cuSvg.src;
  if (lowercaseText.includes("cape verde")) return cvSvg.src;
  if (lowercaseText.includes("curacao")) return cwSvg.src;
  if (lowercaseText.includes("christmas island")) return cxSvg.src;
  if (lowercaseText.includes("cyprus")) return cySvg.src;
  if (lowercaseText.includes("czech republic")) return czSvg.src;
  if (lowercaseText.includes("germany")) return deSvg.src;
  if (lowercaseText.includes("djibouti")) return djSvg.src;
  if (lowercaseText.includes("denmark")) return dkSvg.src;
  if (lowercaseText.includes("dominica")) return dmSvg.src;
  if (lowercaseText.includes("dominican republic")) return doSvg.src;
  if (lowercaseText.includes("algeria")) return dzSvg.src;
  if (lowercaseText.includes("ecuador")) return ecSvg.src;
  if (lowercaseText.includes("estonia")) return eeSvg.src;
  if (lowercaseText.includes("egypt")) return egSvg.src;
  if (lowercaseText.includes("western sahara")) return ehSvg.src;
  if (lowercaseText.includes("eritrea")) return erSvg.src;
  if (lowercaseText.includes("spain")) return esSvg.src;
  if (lowercaseText.includes("ethiopia")) return etSvg.src;
  if (lowercaseText.includes("european union")) return euSvg.src;
  if (lowercaseText.includes("finland")) return fiSvg.src;
  if (lowercaseText.includes("fiji")) return fjSvg.src;
  if (lowercaseText.includes("falkland islands (malvinas)")) return fkSvg.src;
  if (lowercaseText.includes("micronesia, federated states of"))
    return fmSvg.src;
  if (lowercaseText.includes("faroe islands")) return foSvg.src;
  if (lowercaseText.includes("france")) return frSvg.src;
  if (lowercaseText.includes("gabon")) return gaSvg.src;
  if (lowercaseText.includes("england")) return gbEngSvg.src;
  if (lowercaseText.includes("northern ireland")) return gbNirSvg.src;
  if (lowercaseText.includes("scotland")) return gbSctSvg.src;
  if (lowercaseText.includes("wales")) return gbWlsSvg.src;
  if (lowercaseText.includes("united kingdom")) return gbSvg.src;
  if (lowercaseText.includes("grenada")) return gdSvg.src;
  if (lowercaseText.includes("georgia")) return geSvg.src;
  if (lowercaseText.includes("french guiana")) return gfSvg.src;
  if (lowercaseText.includes("guernsey")) return ggSvg.src;
  if (lowercaseText.includes("ghana")) return ghSvg.src;
  if (lowercaseText.includes("gibraltar")) return giSvg.src;
  if (lowercaseText.includes("greenland")) return glSvg.src;
  if (lowercaseText.includes("gambia")) return gmSvg.src;
  if (lowercaseText.includes("guinea")) return gnSvg.src;
  if (lowercaseText.includes("guadeloupe")) return gpSvg.src;
  if (lowercaseText.includes("equatorial guinea")) return gqSvg.src;
  if (lowercaseText.includes("greece")) return grSvg.src;
  if (lowercaseText.includes("south georgia and the south sandwich islands"))
    return gsSvg.src;
  if (lowercaseText.includes("guatemala")) return gtSvg.src;
  if (lowercaseText.includes("guam")) return guSvg.src;
  if (lowercaseText.includes("guinea-bissau")) return gwSvg.src;
  if (lowercaseText.includes("guyana")) return gySvg.src;
  if (lowercaseText.includes("hong kong")) return hkSvg.src;
  if (lowercaseText.includes("heard island and mcdonald islands"))
    return hmSvg.src;
  if (lowercaseText.includes("honduras")) return hnSvg.src;
  if (lowercaseText.includes("croatia")) return hrSvg.src;
  if (lowercaseText.includes("haiti")) return htSvg.src;
  if (lowercaseText.includes("hungary")) return huSvg.src;
  if (lowercaseText.includes("indonesia")) return idSvg.src;
  if (lowercaseText.includes("ireland")) return ieSvg.src;
  if (lowercaseText.includes("israel")) return ilSvg.src;
  if (lowercaseText.includes("isle of man")) return imSvg.src;
  if (lowercaseText.includes("india")) return inSvg.src;
  if (lowercaseText.includes("british indian ocean territory"))
    return ioSvg.src;
  if (lowercaseText.includes("iraq")) return iqSvg.src;
  if (lowercaseText.includes("iran, islamic republic of")) return irSvg.src;
  if (lowercaseText.includes("iceland")) return isSvg.src;
  if (lowercaseText.includes("italy")) return itSvg.src;
  if (lowercaseText.includes("jersey")) return jeSvg.src;
  if (lowercaseText.includes("jamaica")) return jmSvg.src;
  if (lowercaseText.includes("jordan")) return joSvg.src;
  if (lowercaseText.includes("japan")) return jpSvg.src;
  if (lowercaseText.includes("kenya")) return keSvg.src;
  if (lowercaseText.includes("kyrgyzstan")) return kgSvg.src;
  if (lowercaseText.includes("cambodia")) return khSvg.src;
  if (lowercaseText.includes("kiribati")) return kiSvg.src;
  if (lowercaseText.includes("comoros")) return kmSvg.src;
  if (lowercaseText.includes("saint kitts and nevis")) return knSvg.src;
  if (lowercaseText.includes("korea, democratic people's republic of"))
    return kpSvg.src;
  if (lowercaseText.includes("korea, republic of")) return krSvg.src;
  if (lowercaseText.includes("kuwait")) return kwSvg.src;
  if (lowercaseText.includes("cayman islands")) return kySvg.src;
  if (lowercaseText.includes("kazakhstan")) return kzSvg.src;
  if (lowercaseText.includes("lao people's democratic republic"))
    return laSvg.src;
  if (lowercaseText.includes("lebanon")) return lbSvg.src;
  if (lowercaseText.includes("saint lucia")) return lcSvg.src;
  if (lowercaseText.includes("liechtenstein")) return liSvg.src;
  if (lowercaseText.includes("sri lanka")) return lkSvg.src;
  if (lowercaseText.includes("liberia")) return lrSvg.src;
  if (lowercaseText.includes("lesotho")) return lsSvg.src;
  if (lowercaseText.includes("lithuania")) return ltSvg.src;
  if (lowercaseText.includes("luxembourg")) return luSvg.src;
  if (lowercaseText.includes("latvia")) return lvSvg.src;
  if (lowercaseText.includes("libya")) return lySvg.src;
  if (lowercaseText.includes("morocco")) return maSvg.src;
  if (lowercaseText.includes("monaco")) return mcSvg.src;
  if (lowercaseText.includes("moldova, republic of")) return mdSvg.src;
  if (lowercaseText.includes("montenegro")) return meSvg.src;
  if (lowercaseText.includes("saint martin (french part)")) return mfSvg.src;
  if (lowercaseText.includes("madagascar")) return mgSvg.src;
  if (lowercaseText.includes("marshall islands")) return mhSvg.src;
  if (lowercaseText.includes("north macedonia")) return mkSvg.src;
  if (lowercaseText.includes("mali")) return mlSvg.src;
  if (lowercaseText.includes("myanmar")) return mmSvg.src;
  if (lowercaseText.includes("mongolia")) return mnSvg.src;
  if (lowercaseText.includes("macao")) return moSvg.src;
  if (lowercaseText.includes("northern mariana islands")) return mpSvg.src;
  if (lowercaseText.includes("martinique")) return mqSvg.src;
  if (lowercaseText.includes("mauritania")) return mrSvg.src;
  if (lowercaseText.includes("montserrat")) return msSvg.src;
  if (lowercaseText.includes("malta")) return mtSvg.src;
  if (lowercaseText.includes("mauritius")) return muSvg.src;
  if (lowercaseText.includes("maldives")) return mvSvg.src;
  if (lowercaseText.includes("malawi")) return mwSvg.src;
  if (lowercaseText.includes("mexico")) return mxSvg.src;
  if (lowercaseText.includes("malaysia")) return mySvg.src;
  if (lowercaseText.includes("mozambique")) return mzSvg.src;
  if (lowercaseText.includes("namibia")) return naSvg.src;
  if (lowercaseText.includes("new caledonia")) return ncSvg.src;
  if (lowercaseText.includes("niger")) return neSvg.src;
  if (lowercaseText.includes("norfolk island")) return nfSvg.src;
  if (lowercaseText.includes("nigeria")) return ngSvg.src;
  if (lowercaseText.includes("nicaragua")) return niSvg.src;
  if (lowercaseText.includes("netherlands")) return nlSvg.src;
  if (lowercaseText.includes("norway")) return noSvg.src;
  if (lowercaseText.includes("nepal")) return npSvg.src;
  if (lowercaseText.includes("nauru")) return nrSvg.src;
  if (lowercaseText.includes("niue")) return nuSvg.src;
  if (lowercaseText.includes("new zealand")) return nzSvg.src;
  if (lowercaseText.includes("oman")) return omSvg.src;
  if (lowercaseText.includes("panama")) return paSvg.src;
  if (lowercaseText.includes("peru")) return peSvg.src;
  if (lowercaseText.includes("french polynesia")) return pfSvg.src;
  if (lowercaseText.includes("papua new guinea")) return pgSvg.src;
  if (lowercaseText.includes("philippines")) return phSvg.src;
  if (lowercaseText.includes("pakistan")) return pkSvg.src;
  if (lowercaseText.includes("poland")) return plSvg.src;
  if (lowercaseText.includes("saint pierre and miquelon")) return pmSvg.src;
  if (lowercaseText.includes("pitcairn")) return pnSvg.src;
  if (lowercaseText.includes("puerto rico")) return prSvg.src;
  if (lowercaseText.includes("palestine, state of")) return psSvg.src;
  if (lowercaseText.includes("portugal")) return ptSvg.src;
  if (lowercaseText.includes("palau")) return pwSvg.src;
  if (lowercaseText.includes("paraguay")) return pySvg.src;
  if (lowercaseText.includes("qatar")) return qaSvg.src;
  if (lowercaseText.includes("reunion")) return reSvg.src;
  if (lowercaseText.includes("romania")) return roSvg.src;
  if (lowercaseText.includes("serbia")) return rsSvg.src;
  if (lowercaseText.includes("russian federation")) return ruSvg.src;
  if (lowercaseText.includes("rwanda")) return rwSvg.src;
  if (lowercaseText.includes("saudi arabia")) return saSvg.src;
  if (lowercaseText.includes("solomon islands")) return sbSvg.src;
  if (lowercaseText.includes("seychelles")) return scSvg.src;
  if (lowercaseText.includes("sudan")) return sdSvg.src;
  if (lowercaseText.includes("sweden")) return seSvg.src;
  if (lowercaseText.includes("singapore")) return sgSvg.src;
  if (lowercaseText.includes("saint helena, ascension and tristan da cunha"))
    return shSvg.src;
  if (lowercaseText.includes("slovenia")) return siSvg.src;
  if (lowercaseText.includes("svalbard and jan mayen")) return sjSvg.src;
  if (lowercaseText.includes("slovakia")) return skSvg.src;
  if (lowercaseText.includes("sierra leone")) return slSvg.src;
  if (lowercaseText.includes("san marino")) return smSvg.src;
  if (lowercaseText.includes("senegal")) return snSvg.src;
  if (lowercaseText.includes("somalia")) return soSvg.src;
  if (lowercaseText.includes("suriname")) return srSvg.src;
  if (lowercaseText.includes("south sudan")) return ssSvg.src;
  if (lowercaseText.includes("sao tome and principe")) return stSvg.src;
  if (lowercaseText.includes("el salvador")) return svSvg.src;
  if (lowercaseText.includes("sint maarten (dutch part)")) return sxSvg.src;
  if (lowercaseText.includes("syrian arab republic")) return sySvg.src;
  if (lowercaseText.includes("eswatini")) return szSvg.src;
  if (lowercaseText.includes("turks and caicos islands")) return tcSvg.src;
  if (lowercaseText.includes("chad")) return tdSvg.src;
  if (lowercaseText.includes("french southern territories")) return tfSvg.src;
  if (lowercaseText.includes("togo")) return tgSvg.src;
  if (lowercaseText.includes("thailand")) return thSvg.src;
  if (lowercaseText.includes("tajikistan")) return tjSvg.src;
  if (lowercaseText.includes("tokelau")) return tkSvg.src;
  if (lowercaseText.includes("timor-leste")) return tlSvg.src;
  if (lowercaseText.includes("turkmenistan")) return tmSvg.src;
  if (lowercaseText.includes("tunisia")) return tnSvg.src;
  if (lowercaseText.includes("tonga")) return toSvg.src;
  if (lowercaseText.includes("turkey")) return trSvg.src;
  if (lowercaseText.includes("trinidad and tobago")) return ttSvg.src;
  if (lowercaseText.includes("tuvalu")) return tvSvg.src;
  if (lowercaseText.includes("taiwan, province of china")) return twSvg.src;
  if (lowercaseText.includes("tanzania, united republic of")) return tzSvg.src;
  if (lowercaseText.includes("ukraine")) return uaSvg.src;
  if (lowercaseText.includes("uganda")) return ugSvg.src;
  if (lowercaseText.includes("united states minor outlying islands"))
    return umSvg.src;
  if (lowercaseText.includes("united states")) return usSvg.src;
  if (lowercaseText.includes("uruguay")) return uySvg.src;
  if (lowercaseText.includes("uzbekistan")) return uzSvg.src;
  if (lowercaseText.includes("holy see (vatican city state)")) return vaSvg.src;
  if (lowercaseText.includes("saint vincent and the grenadines"))
    return vcSvg.src;
  if (lowercaseText.includes("venezuela")) return veSvg.src;
  if (lowercaseText.includes("virgin islands, british")) return vgSvg.src;
  if (lowercaseText.includes("virgin islands, u.s.")) return viSvg.src;
  if (lowercaseText.includes("viet nam")) return vnSvg.src;
  if (lowercaseText.includes("vanuatu")) return vuSvg.src;
  if (lowercaseText.includes("wallis and futuna")) return wfSvg.src;
  if (lowercaseText.includes("samoa")) return wsSvg.src;
  if (lowercaseText.includes("kosovo")) return xkSvg.src;
  if (lowercaseText.includes("yemen")) return yeSvg.src;
  if (lowercaseText.includes("mayotte")) return ytSvg.src;
  if (lowercaseText.includes("south africa")) return zaSvg.src;
  if (lowercaseText.includes("zambia")) return zmSvg.src;
  if (lowercaseText.includes("zimbabwe")) return zwSvg.src;

  return notFoundSvg.src;
}
