name: Build and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      PREVIEW: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v23
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install --include=dev --frozen-lockfile --non-interactive

      - name: Check code formatting
        run: npm run lint

      - name: Install Playwright Firefox browser
        run: npx playwright install --with-deps firefox

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: playwright-test-results/
          retention-days: 30